version: "3.8"

services:
  rag-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./data:/app/data:ro
